{pkgs, ...}: let
  rtkBin = "${pkgs.rtk}/bin/rtk";

  rtkMd = ''
    # RTK - Rust Token Killer

    **Usage**: Token-optimized CLI proxy (60-90% savings on dev operations)

    ## Meta Commands (always use rtk directly)

    ```bash
    rtk gain              # Show token savings analytics
    rtk gain --history    # Show command usage history with savings
    rtk discover          # Analyze Claude Code history for missed opportunities
    rtk proxy <cmd>       # Execute raw command without filtering (for debugging)
    ```

    ## Installation Verification

    ```bash
    rtk --version         # Should show: rtk X.Y.Z
    rtk gain              # Should work (not "command not found")
    which rtk             # Verify correct binary
    ```

    ⚠️ **Name collision**: If `rtk gain` fails, you may have reachingforthejack/rtk (Rust Type Kit) installed instead.

    ## Hook-Based Usage

    All other commands are automatically rewritten by the hook.
    Example: `git status` → `rtk git status` (transparent, 0 tokens overhead)
  '';

  # Generated by: rtk init --no-patch --opencode --agent claude -g
  opencodeRtkPlugin = ''
    import type { Plugin } from "@opencode-ai/plugin"

    // RTK OpenCode plugin — rewrites commands to use rtk for token savings.
    // Requires: rtk >= 0.23.0 in PATH.
    //
    // This is a thin delegating plugin: all rewrite logic lives in `rtk rewrite`,
    // which is the single source of truth (src/discover/registry.rs).
    // To add or change rewrite rules, edit the Rust registry — not this file.

    export const RtkOpenCodePlugin: Plugin = async ({ $ }) => {
      try {
        await $`which rtk`.quiet()
      } catch {
        console.warn("[rtk] rtk binary not found in PATH — plugin disabled")
        return {}
      }

      return {
        "tool.execute.before": async (input, output) => {
          const tool = String(input?.tool ?? "").toLowerCase()
          if (tool !== "bash" && tool !== "shell") return
          const args = output?.args
          if (!args || typeof args !== "object") return

          const command = (args as Record<string, unknown>).command
          if (typeof command !== "string" || !command) return

          try {
            const result = await $`rtk rewrite ''${command}`.quiet().nothrow()
            const rewritten = String(result.stdout).trim()
            if (rewritten && rewritten !== command) {
              ;(args as Record<string, unknown>).command = rewritten
            }
          } catch {
            // rtk rewrite failed — pass through unchanged
          }
        },
      }
    }
  '';
in {
  home.packages = [pkgs.rtk];

  programs.claude-code = {
    context = rtkMd;
    settings.hooks.PreToolUse = [
      {
        matcher = "Bash";
        hooks = [
          {
            type = "command";
            command = "${rtkBin} hook claude";
          }
        ];
      }
    ];
  };

  xdg.configFile."opencode/plugins/rtk.ts".text = opencodeRtkPlugin;
}
